### ISSUE TITLE
Stop working for the latest Teams app 3.13.0

### ISSUE THREAD

**Issue by MaksCheck** [haoict/microsoft-detection-bypass#10]
---
name: Bug report
about: Report a bug
title: ''
labels: bug
assignees: ''

---

### Environment
- Platform+version: **iOS 14** 
- Tweak version: **1.0.4** 
- Do you have jailbreak detection bypass tweaks (FlyJB, HideJB, kernbypass, ...): **No**
- If yes, are you sure that it does not block this tweak: **Yes/No**

### Bug Report

Note: Providing steps to reproduce, screenshot or screen recording are always helpful!

**Comment by haoict** [comment]
I updated the tweak version to 1.0.5. Please check. Thanks

**Comment by MaksCheck** [comment]
Works great! Thank you!!!
