### ISSUE TITLE
Adding support of Power BI app

### ISSUE THREAD

**Issue by MaksCheck** [haoict/microsoft-detection-bypass#11]
**Is your feature request related to a problem? Please describe.**
Please add support of another Microsoft app - Power BI

**Describe the solution you'd like**
Adding support in the current tweak

**Describe alternatives you've considered**
Up to you

**Additional context**
Amazing tweak, great job from developer, I'm ready to pay for that, worth it. Thanks to you!

**Comment by haoict** [comment]
Done. Please check:
https://github.com/haoict/microsoft-detection-bypass/releases/tag/v1.0.5

**Comment by MaksCheck** [comment]
Works perfect! Thank you for your amazing work
