### ISSUE TITLE
Stop working for the latest versions: Edge, Sharepoint, Onedrive, Teams. Detect jb

### ISSUE THREAD

**Issue by MaksCheck** [haoict/microsoft-detection-bypass#12]
---
name: Bug report
about: Report a bug
title: ''
labels: bug
assignees: ''

---

### Environment
- Platform+version: **iOS 14** 
- Tweak version: **0.0.0** 
- Do you have jailbreak detection bypass tweaks (FlyJB, HideJB, kernbypass, ...): **No**
- If yes, are you sure that it does not block this tweak: **No**

### Bug Report

Note: Providing steps to reproduce, screenshot or screen recording are always helpful!
When you open Edge or Sharepoint, warning message about jailbreak is appear.

**Comment by shadowscott** [comment]
Working in Teams 3.13.0 but not in 3.13.1

**Comment by MaksCheck** [comment]
I found that flex patch from MR_Darren is working for any version of Sharepoint. Maybe it's worth to look into this patch to find a long term solution for other apps.
