### ISSUE TITLE
Teams not working, jailbreak is detected

### ISSUE THREAD

**Issue by parveen140396** [haoict/microsoft-detection-bypass#13]
### Environment
- Platform+version: **iOS 13.5** 
- Tweak version: **1.0.5** 
- Do you have jailbreak detection bypass tweaks (FlyJB, HideJB, kernbypass, ...): **No**

### Bug Report

Note: Providing steps to reproduce, screenshot or screen recording are always helpful!

**Comment by Cazforshort** [comment]
Can confirm

**Comment by haoict** [comment]
Please update the tweak.
