### ISSUE TITLE
New update of microsoft-detection-bypass is not working for me

### ISSUE THREAD

**Issue by didlika** [haoict/microsoft-detection-bypass#14]
### Environment
- Platform+version: **iOS 14.3** 
- Tweak version: **1.0.6** 
- Do you have jailbreak detection bypass tweaks (FlyJB, HideJB, kernbypass, ...): **No**

### Bug Report

This morning I had updated tweak to 1.0.6 and both teams and outlook stopped working for me. With 1.0.5, everything was working. Tried updating outlook to the latest version, same issue, tried downgrading also, same issue.

**Comment by haoict** [comment]
Please reinstall version "1.0.6~fix"
Thanks for reporting the issue.
