### ISSUE TITLE
New update is not working

### ISSUE THREAD

**Issue by NunoMF** [haoict/microsoft-detection-bypass#15]
### Environment
- Platform+version: **iOS 14.3
- Tweak version: **1.0.6 
- Do you have jailbreak detection bypass tweaks (FlyJB, HideJB, kernbypass, ...): **Yes
- If yes, are you sure that it does not block this tweak: **Yes/
- 

### Bug Report
Before update to version 1.0.6 outlook and teams works fine. After the update both stop working and jailbreak is detected. 

Note: Providing steps to reproduce, screenshot or screen recording are always helpful!

**Comment by haoict** [comment]
Please reinstall version "1.0.6~fix"
Thanks for reporting the issue.
