### ISSUE TITLE
Long term solution

### ISSUE THREAD

**Issue by MaksCheck** [haoict/microsoft-detection-bypass#17]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I found that flex patch from MR_Darren is working for any version of Sharepoint. Maybe it's worth to look into this patch to find a long term solution for other apps.

**Comment by haoict** [comment]
Hi,
What's the flex patch name?

**Comment by MaksCheck** [comment]
Sharepoint, Bypass Jailbreak Detection 2021. ![image](https://user-images.githubusercontent.com/25697390/132004276-243d4a1d-a2c6-4dea-b26e-9886fabe0a70.jpeg)

**Comment by haoict** [comment]
@MaksCheck 
I checked that, that doesn't help as my code already covered those methods in the patch.

**Comment by MaksCheck** [comment]
> @MaksCheck 
> 
> I checked that, that doesn't help as my code already covered those methods in the patch.

Hi, this is strange, because when I switch off this flex patch, app detects jailbreak. If you say this approach is already in your tweak, when it should work. But it doesn't. Thank you anyway, you do a great work!

**Comment by MaksCheck** [comment]
@haoict 
Hi, just updated Sharepoint to the new version and it still works with flex patch. If I turn off flex patch app detects jailbreak. Your tweak (latest version) is installed. Something is wrong if you are saying that your tweak is already covering this approach.
