### ISSUE TITLE
Yammer support

### ISSUE THREAD

**Issue by L0rdLogan** [haoict/microsoft-detection-bypass#7]
**Is your feature request related to a problem? Please describe.**
Please add Yammer support, all other apps are bypassed except Yammer.

**Describe the solution you'd like**
Add Microsoft Yammer app support

**Describe alternatives you've considered**
Tried using Yammer with A-Bypass and Hestia - both are detected

**Additional context**
I tried A-bypass again and it worked, Still, native support would be great

**Comment by haoict** [comment]
Added support for Yammer in tweak version v1.0.3
