### ISSUE TITLE
Stopped working for latest Trams update

### ISSUE THREAD

**Issue by didlika** [haoict/microsoft-detection-bypass#8]
### Environment
- Platform+version: **iOS 14.3** 
- Tweak version: **1.0.2** 
- Do you have jailbreak detection bypass tweaks (FlyJB, HideJB, kernbypass, ...): **No**

### Bug Report

Steps to reproduce:
- Update Teams to the latestt version. 
- Open Teams
>>BUG>> jailbreak detected

**Comment by shadowscott** [comment]
I can confirm this is happening as well. Had to downgrade

**Comment by MaksCheck** [comment]
Hi, same for me. JB detected after teams opening. I can't downgrade to the lowest version of teams.

**Comment by haoict** [comment]
Updated to v1.0.3. Should fix the problem :)
