### ISSUE TITLE
Stopped working for latest Outlook update

### ISSUE THREAD

**Issue by didlika** [haoict/microsoft-detection-bypass#9]
Environment
Platform+version: iOS 14.3
Tweak version: 1.0.3
Do you have jailbreak detection bypass tweaks (FlyJB, HideJB, kernbypass, ...): No
Bug Report
Steps to reproduce:

Update Outlook to the latest version.
Open Outlook
BUG>> jailbreak detected

**Comment by haoict** [comment]
Updated the tweak to v1.0.4. Should fix the problem
